name: Patch workflow
on:
  workflow_dispatch:

jobs:
  gcp_trigger:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/patch/')
    steps:
      - name: Check patch branch
        run: |
          echo "Patch workflow was run on: ${{ github.ref_name }}"

      - name: Run gcp trigger
        run: |
          echo "🚀 Запуск задачи на ветке ${{ github.event.inputs.branch }}"
          # Вставь свою кастомную логику сюда
