name: Patch workflow
on:
  workflow_dispatch:

jobs:
  gcp_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check patch branch
        run: |
          echo "Patch workflow was run on: ${{ github.event.inputs.branch }}"
          if [[ "${{ github.event.inputs.branch }}" != patch/* ]]; then
            echo "Error: patch branch name shoud start from 'patch/'"
            exit 1
          fi

      - name: Run gcp trigger
        run: |
          echo "🚀 Запуск задачи на ветке ${{ github.event.inputs.branch }}"
          # Вставь свою кастомную логику сюда
