name: Patch workflow
on:
  workflow_dispatch:

jobs:
  gcp_trigger:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/patch/')
    steps:
      - name: Run GCP trigger
        run: |
          echo "Patch workflow was run on: ${{ github.ref_name }}"
