name: Patch workflow
on:
  workflow_dispatch:

jobs:
  gcp_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check patch branch
        run: |
          echo "Selected patch branch: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" != patch/* ]]; then
            echo "Error: Invalid branch name: '${{ github.ref_name }}'"
            echo "Branch name must start with 'patch/' (e.g., patch/v1.2)"
            exit 1
          fi
          if [[ ! "${{ github.ref_name }}" =~ ^patch/v[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: '${{ github.ref_name }}'"
            echo "The version must follow the format 'patch/vX.Y' (e.g., patch/v0.2, patch/v4.3)."
          exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CLOUD_BUILD_KEY }}'

      - name: Trigger GCP Cloud Build
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |
          echo "Triggering GCP build for branch: $BRANCH_NAME"
          gcloud builds triggers list --project=norse-antenna-388317
            --region=us-east1 \
            --branch="$BRANCH_NAME" \
            --project="$PROJECT_ID"
